In [1]:
import numpy as np

Створіть масив зі 100 елементів – курсу євро щодо гривні(припустимо , що значення розподілені за рівномірним законом між 28.75 та 31)

In [2]:
arr = np.random.uniform(low = 28.75,high =31, size=100)
arr

array([29.21496134, 29.5456659 , 30.61749579, 29.60607641, 30.99440469,
       29.80391791, 29.38598784, 30.00157375, 29.29968385, 30.95458217,
       30.28290949, 29.7924002 , 30.94887822, 30.305533  , 29.58026914,
       28.78325765, 30.83943775, 29.81948336, 30.11912756, 30.67793512,
       29.94543594, 30.06269497, 30.11949766, 28.86604527, 30.09455603,
       29.7268668 , 30.44257746, 30.4183391 , 30.06631003, 29.75350002,
       30.8089917 , 29.43852403, 30.42429064, 29.01356012, 30.3811545 ,
       29.43459881, 29.50488428, 28.87577636, 30.29580406, 29.10795573,
       29.45231137, 29.81730543, 29.23541009, 30.60693386, 30.64905152,
       29.19295734, 30.67942395, 29.57050722, 29.6487508 , 29.22051064,
       30.57022158, 29.95952449, 29.35737535, 30.620303  , 30.15465849,
       30.14019669, 30.82892681, 29.0624768 , 29.29455917, 29.91875123,
       30.13983885, 29.57770891, 30.00746968, 30.7497055 , 30.84790874,
       28.93202992, 29.9430917 , 30.40616044, 29.01066885, 30.78

Знайдіть середній та медіанний курс за вибіркою

In [3]:
arr.mean()

29.93590163879778

In [4]:
np.median(arr)

29.952480216151265

Знайдіть розмах (різниця між максимальним та мінімальним курсом) вибірки

In [5]:
arr.min()-arr.max()

-2.211147044987886

Який відсоток значень а) понад 30; б) трохи більше 29?

In [6]:
over_30 = len(arr[arr>30])/len(arr)*100
over_30

48.0

In [7]:
over_29 = len(arr[(arr>29) & (arr<29.4)])/len(arr)*100
over_29

19.0

Чи зустрічається у вибірці число 30?

In [8]:
30 in arr

False

Відсортуйте значення за зростанням. Знайдіть відстані між а) першим та п'ятим
елементами; б) третім з кінця та останнім елементами відсортованого масиву.

In [9]:
arr = np.sort(arr)
arr

array([28.78325765, 28.86604527, 28.87577636, 28.88898575, 28.93202992,
       29.01066885, 29.01356012, 29.04707432, 29.0624768 , 29.10795573,
       29.10976602, 29.19295734, 29.21496134, 29.22051064, 29.23262125,
       29.23541009, 29.280025  , 29.28201113, 29.29455917, 29.29968385,
       29.31373298, 29.34931422, 29.35737535, 29.38598784, 29.43459881,
       29.43852403, 29.44156611, 29.45231137, 29.46134906, 29.50488428,
       29.5456659 , 29.57050722, 29.57770891, 29.58026914, 29.59476442,
       29.60607641, 29.61700114, 29.63940865, 29.6487508 , 29.70087673,
       29.7268668 , 29.75350002, 29.7924002 , 29.80391791, 29.81730543,
       29.81948336, 29.88829701, 29.91875123, 29.9430917 , 29.94543594,
       29.95952449, 29.98890276, 30.00157375, 30.00746968, 30.06269497,
       30.06346737, 30.06631003, 30.075976  , 30.08652278, 30.09455603,
       30.11912756, 30.11949766, 30.13983885, 30.14019669, 30.15465849,
       30.23817307, 30.28290949, 30.29580406, 30.29720281, 30.30

In [10]:
np.sqrt((arr[4]**2-arr[0]**2))

2.930261824260605

In [11]:
np.sqrt((arr[-1]**2-arr[-3]**2))

0.8178804951936465

Додайте до вибірки ще 20 значень - випадкових чисел з нормальним розподілом із середнім 30 та стандартним відхиленням 1.5.

In [12]:
extra_arr = np.random.normal(loc=30, scale=1.5, size=20)
extra_arr

array([31.3340862 , 27.9734106 , 29.47588415, 25.85063295, 30.81858327,
       28.70114798, 28.57326777, 30.58237822, 27.5637904 , 29.76995383,
       29.16725166, 30.155743  , 31.77734702, 29.44485908, 26.94049212,
       30.48109354, 29.00756279, 27.76684863, 29.51527407, 31.51012494])

In [13]:
arr = np.concatenate((arr,extra_arr))
arr

array([28.78325765, 28.86604527, 28.87577636, 28.88898575, 28.93202992,
       29.01066885, 29.01356012, 29.04707432, 29.0624768 , 29.10795573,
       29.10976602, 29.19295734, 29.21496134, 29.22051064, 29.23262125,
       29.23541009, 29.280025  , 29.28201113, 29.29455917, 29.29968385,
       29.31373298, 29.34931422, 29.35737535, 29.38598784, 29.43459881,
       29.43852403, 29.44156611, 29.45231137, 29.46134906, 29.50488428,
       29.5456659 , 29.57050722, 29.57770891, 29.58026914, 29.59476442,
       29.60607641, 29.61700114, 29.63940865, 29.6487508 , 29.70087673,
       29.7268668 , 29.75350002, 29.7924002 , 29.80391791, 29.81730543,
       29.81948336, 29.88829701, 29.91875123, 29.9430917 , 29.94543594,
       29.95952449, 29.98890276, 30.00157375, 30.00746968, 30.06269497,
       30.06346737, 30.06631003, 30.075976  , 30.08652278, 30.09455603,
       30.11912756, 30.11949766, 30.13983885, 30.14019669, 30.15465849,
       30.23817307, 30.28290949, 30.29580406, 30.29720281, 30.30

Створіть матрицю розміром 20 × 4 із нормального розподілу із середнім μ= 10 та
стандартним відхиленням σ = 2.5.

In [14]:
matrix  = np.random.normal(loc=10, scale=2.5, size=(20,4))
matrix

array([[ 6.02760087, 12.68027705,  9.88299787, 10.72814249],
       [ 8.00416978, 12.64436068,  6.35436426, 11.715443  ],
       [ 7.62745301, 10.20582081, 11.73806448,  9.94569507],
       [12.7972757 ,  8.60746952,  9.54803562, 12.14407122],
       [ 9.19080775,  9.51635785, 10.00068975, 10.28609556],
       [ 8.56622081,  8.6679404 ,  4.62190536,  8.63517818],
       [ 5.74260639,  5.17175399,  6.30205602,  7.45199908],
       [13.10070348, 10.80609616, 10.09408643,  8.38569514],
       [12.81982703,  9.79117936, 12.39827078,  7.68369447],
       [ 7.45155519, 11.72717012, 10.67469899, 10.15212118],
       [ 9.88625414,  9.62691254, 11.0932987 ,  8.94766812],
       [ 7.1520068 ,  8.43672968, 10.57725971, 11.26673045],
       [11.93140474, 11.7829107 ,  9.88362432, 10.47153188],
       [13.62750029, 10.41793211,  6.97545741,  1.70389134],
       [13.00940596,  8.42616718,  9.04144361, 11.66567509],
       [15.73977677,  7.41319988,  7.40881078, 11.97873147],
       [ 9.40336203,  7.

Знайдіть суму елементів першого рядка

In [15]:
np.sum(matrix[0])

39.319018275366616

Знайдіть максимальний елемент останнього стовпця

In [16]:
np.max(matrix[:,-1])

13.044995653950815

Знайдіть середнє значення у кожному рядку

In [17]:
np.mean(matrix, axis=1)

array([ 9.82975457,  9.67958443,  9.87925834, 10.77421302,  9.74848773,
        7.62281119,  6.16710387, 10.5966453 , 10.67324291, 10.00138637,
        9.88853337,  9.35818166, 11.01736791,  8.18119529, 10.53567296,
       10.63512973,  9.09200952, 11.29689046, 10.70297931, 11.63787797])

Створіть нову матрицю того ж розміру, елементи якої обчислюються за правилом: bij = aij − min, де aij - елементи вихідної матриці, min - її мінімальний елемент.

In [18]:
min_value = matrix.min()
new_matrix = matrix - min_value
new_matrix

array([[ 4.32370953, 10.97638571,  8.17910653,  9.02425115],
       [ 6.30027844, 10.94046935,  4.65047292, 10.01155166],
       [ 5.92356167,  8.50192948, 10.03417314,  8.24180373],
       [11.09338437,  6.90357819,  7.84414428, 10.44017988],
       [ 7.48691641,  7.81246652,  8.29679841,  8.58220422],
       [ 6.86232948,  6.96404906,  2.91801403,  6.93128684],
       [ 4.03871505,  3.46786265,  4.59816468,  5.74810775],
       [11.39681214,  9.10220482,  8.39019509,  6.6818038 ],
       [11.11593569,  8.08728803, 10.69437945,  5.97980313],
       [ 5.74766386, 10.02327878,  8.97080765,  8.44822985],
       [ 8.1823628 ,  7.9230212 ,  9.38940736,  7.24377678],
       [ 5.44811546,  6.73283834,  8.87336837,  9.56283912],
       [10.22751341, 10.07901937,  8.17973298,  8.76764054],
       [11.92360895,  8.71404077,  5.27156607,  0.        ],
       [11.30551462,  6.72227585,  7.33755228,  9.96178376],
       [14.03588544,  5.70930854,  5.70491944, 10.27484014],
       [ 7.69947069,  5.

Знайдіть рядки, третій елемент яких більший за 5

In [19]:
new_matrix[new_matrix[:,2]>5]

array([[ 4.32370953, 10.97638571,  8.17910653,  9.02425115],
       [ 5.92356167,  8.50192948, 10.03417314,  8.24180373],
       [11.09338437,  6.90357819,  7.84414428, 10.44017988],
       [ 7.48691641,  7.81246652,  8.29679841,  8.58220422],
       [11.39681214,  9.10220482,  8.39019509,  6.6818038 ],
       [11.11593569,  8.08728803, 10.69437945,  5.97980313],
       [ 5.74766386, 10.02327878,  8.97080765,  8.44822985],
       [ 8.1823628 ,  7.9230212 ,  9.38940736,  7.24377678],
       [ 5.44811546,  6.73283834,  8.87336837,  9.56283912],
       [10.22751341, 10.07901937,  8.17973298,  8.76764054],
       [11.92360895,  8.71404077,  5.27156607,  0.        ],
       [11.30551462,  6.72227585,  7.33755228,  9.96178376],
       [14.03588544,  5.70930854,  5.70491944, 10.27484014],
       [ 7.69947069,  5.89014923, 11.78278847,  4.18006433],
       [ 8.57976235,  9.99932013,  9.95740475,  9.83550926],
       [10.83273721,  4.95804675,  8.86446361, 11.34110432],
       [11.24092839,  9.

In [20]:
np.where(new_matrix[:, 2] > 5)

(array([ 0,  2,  3,  4,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       dtype=int64),)

Знайдіть стовпці, максимальний елемент яких більший за 12

In [21]:
np.where(np.max(new_matrix,axis=0)>12)

(array([0], dtype=int64),)

In [22]:
np.max(new_matrix,axis=0)>12

array([ True, False, False, False])

In [23]:
new_matrix[:,2]>5

array([ True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])